### ISSUE TITLE
How can I implemented files tree for DocumentFile[]

### ISSUE THREAD

**Issue by kisonix** [ikws4/TreeView#1]
I've tried many times to list DocumentFile[] which is provided by StorageAccessFramework to avoid some storage restricted in newer API lvl and also access the termux's home dir

Could you help me a bit:)

![IMG_20220725_121554](https://user-images.githubusercontent.com/109852917/180706669-d33c3f5b-9078-42eb-86f8-76519750a344.jpg)

**Comment by ikws4** [comment]
I just added the sample code for this, please take look at [DocumentFileTreeAdapter](https://github.com/ikws4/TreeView/blob/main/app/src/main/java/io/github/ikws4/treeview/documentfile/DocumentFileTreeAdapter.java)

**Comment by kisonix** [comment]
> I just added the sample code for this, please take look at [DocumentFileTreeAdapter](https://github.com/ikws4/TreeView/blob/main/app/src/main/java/io/github/ikws4/treeview/documentfile/DocumentFileTreeAdapter.java)

Oh thanks man I really appreciate it.
